#############################################################################
# Makefile for building: xn.app/Contents/MacOS/xn
# Generated by qmake (2.01a) (Qt 4.3.0) on: Sat Jun 7 16:24:00 2008
# Project:  xn.pro
# Template: app
# Command: /usr/local/trolltech/qt-4.3.0/bin/qmake -macx -o Makefile xn.pro
#############################################################################

####### Compiler, tools and options

CC            = cc
CXX           = c++
DEFINES       = -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.3.0/mkspecs/macx-g++ -I. -I/usr/local/Trolltech/Qt-4.3.0/include/QtCore -I/usr/local/Trolltech/Qt-4.3.0/include/QtCore -I/usr/local/Trolltech/Qt-4.3.0/include/QtGui -I/usr/local/Trolltech/Qt-4.3.0/include/QtGui -I/usr/local/Trolltech/Qt-4.3.0/include/QtXml -I/usr/local/Trolltech/Qt-4.3.0/include/QtXml -I/usr/local/Trolltech/Qt-4.3.0/include -I. -I. -I.
LINK          = c++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.3.0/lib -lQtXml_debug -L/usr/local/Trolltech/Qt-4.3.0/lib -lQtGui_debug -framework Carbon -framework AppKit -lQtCore_debug -lz -lm -framework ApplicationServices
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/trolltech/qt-4.3.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = dtneuron.cpp \
		edgeconfiguration.cpp \
		ednetwork.cpp \
		ednetworkmember.cpp \
		edsubnetwork.cpp \
		greyscalewindow.cpp \
		main.cpp \
		nedtreeview.cpp \
		neuron.cpp \
		traindialog.cpp \
		xnned.cpp moc_nedtreeview.cpp \
		moc_traindialog.cpp \
		moc_xnned.cpp
OBJECTS       = dtneuron.o \
		edgeconfiguration.o \
		ednetwork.o \
		ednetworkmember.o \
		edsubnetwork.o \
		greyscalewindow.o \
		main.o \
		nedtreeview.o \
		neuron.o \
		traindialog.o \
		xnned.o \
		moc_nedtreeview.o \
		moc_traindialog.o \
		moc_xnned.o
DIST          = /usr/local/Trolltech/Qt-4.3.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/common/mac-g++.conf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/mac/rez.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/lex.prf \
		xn.pro
QMAKE_TARGET  = xn
DESTDIR       = 
TARGET        = xn.app/Contents/MacOS/xn

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile xn.app/Contents/PkgInfo xn.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) xn.app/Contents/MacOS/ || $(MKDIR) xn.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: xn.pro  /usr/local/Trolltech/Qt-4.3.0/mkspecs/macx-g++/qmake.conf /usr/local/Trolltech/Qt-4.3.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/common/mac-g++.conf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/mac/rez.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.3.0/lib/libQtXml_debug.prl \
		/usr/local/Trolltech/Qt-4.3.0/lib/libQtCore_debug.prl \
		/usr/local/Trolltech/Qt-4.3.0/lib/libQtGui_debug.prl
	$(QMAKE) -macx -o Makefile xn.pro
/usr/local/Trolltech/Qt-4.3.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/common/mac.conf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/common/mac-g++.conf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/mac/default_pre.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/mac/default_post.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/mac/objective_c.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/mac/rez.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/mac/sdk.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.3.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.3.0/lib/libQtXml_debug.prl:
/usr/local/Trolltech/Qt-4.3.0/lib/libQtCore_debug.prl:
/usr/local/Trolltech/Qt-4.3.0/lib/libQtGui_debug.prl:
qmake:  FORCE
	@$(QMAKE) -macx -o Makefile xn.pro

xn.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) xn.app/Contents || $(MKDIR) xn.app/Contents 
	@$(DEL_FILE) xn.app/Contents/PkgInfo
	@echo "APPL????" >xn.app/Contents/PkgInfo
xn.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) xn.app/Contents || $(MKDIR) xn.app/Contents 
	@$(DEL_FILE) xn.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,xn,g" -e "s,@TYPEINFO@,????,g" /usr/local/Trolltech/Qt-4.3.0/mkspecs/macx-g++/Info.plist.app >xn.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/xn1.0.0 || $(MKDIR) .tmp/xn1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/xn1.0.0/ && $(COPY_FILE) --parents dtneuron.h edgeconfiguration.h ednetwork.h ednetworkmember.h edsubnetwork.h globals.h greyscalewindow.h nedtreeview.h neuron.h traindialog.h xnned.h .tmp/xn1.0.0/ && $(COPY_FILE) --parents dtneuron.cpp edgeconfiguration.cpp ednetwork.cpp ednetworkmember.cpp edsubnetwork.cpp greyscalewindow.cpp main.cpp nedtreeview.cpp neuron.cpp traindialog.cpp xnned.cpp .tmp/xn1.0.0/ && $(COPY_FILE) --parents xn_ru.ts .tmp/xn1.0.0/ && (cd `dirname .tmp/xn1.0.0` && $(TAR) xn1.0.0.tar xn1.0.0 && $(COMPRESS) xn1.0.0.tar) && $(MOVE) `dirname .tmp/xn1.0.0`/xn1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/xn1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r xn.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_nedtreeview.cpp moc_traindialog.cpp moc_xnned.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_nedtreeview.cpp moc_traindialog.cpp moc_xnned.cpp
moc_nedtreeview.cpp: ednetwork.h \
		globals.h \
		greyscalewindow.h \
		ednetworkmember.h \
		edgeconfiguration.h \
		edsubnetwork.h \
		neuron.h \
		dtneuron.h \
		nedtreeview.h
	/usr/local/Trolltech/Qt-4.3.0/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ nedtreeview.h -o moc_nedtreeview.cpp

moc_traindialog.cpp: ednetwork.h \
		globals.h \
		greyscalewindow.h \
		ednetworkmember.h \
		edgeconfiguration.h \
		edsubnetwork.h \
		neuron.h \
		dtneuron.h \
		traindialog.h
	/usr/local/Trolltech/Qt-4.3.0/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ traindialog.h -o moc_traindialog.cpp

moc_xnned.cpp: ednetwork.h \
		globals.h \
		greyscalewindow.h \
		ednetworkmember.h \
		edgeconfiguration.h \
		edsubnetwork.h \
		neuron.h \
		dtneuron.h \
		traindialog.h \
		nedtreeview.h \
		xnned.h
	/usr/local/Trolltech/Qt-4.3.0/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ xnned.h -o moc_xnned.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

dtneuron.o: dtneuron.cpp dtneuron.h \
		globals.h \
		ednetworkmember.h \
		edgeconfiguration.h \
		greyscalewindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dtneuron.o dtneuron.cpp

edgeconfiguration.o: edgeconfiguration.cpp edgeconfiguration.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edgeconfiguration.o edgeconfiguration.cpp

ednetwork.o: ednetwork.cpp ednetwork.h \
		globals.h \
		greyscalewindow.h \
		ednetworkmember.h \
		edgeconfiguration.h \
		edsubnetwork.h \
		neuron.h \
		dtneuron.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ednetwork.o ednetwork.cpp

ednetworkmember.o: ednetworkmember.cpp ednetworkmember.h \
		globals.h \
		edgeconfiguration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ednetworkmember.o ednetworkmember.cpp

edsubnetwork.o: edsubnetwork.cpp edsubnetwork.h \
		globals.h \
		ednetworkmember.h \
		edgeconfiguration.h \
		neuron.h \
		greyscalewindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edsubnetwork.o edsubnetwork.cpp

greyscalewindow.o: greyscalewindow.cpp greyscalewindow.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o greyscalewindow.o greyscalewindow.cpp

main.o: main.cpp xnned.h \
		ednetwork.h \
		globals.h \
		greyscalewindow.h \
		ednetworkmember.h \
		edgeconfiguration.h \
		edsubnetwork.h \
		neuron.h \
		dtneuron.h \
		traindialog.h \
		nedtreeview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

nedtreeview.o: nedtreeview.cpp nedtreeview.h \
		ednetwork.h \
		globals.h \
		greyscalewindow.h \
		ednetworkmember.h \
		edgeconfiguration.h \
		edsubnetwork.h \
		neuron.h \
		dtneuron.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nedtreeview.o nedtreeview.cpp

neuron.o: neuron.cpp neuron.h \
		globals.h \
		greyscalewindow.h \
		edgeconfiguration.h \
		ednetworkmember.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neuron.o neuron.cpp

traindialog.o: traindialog.cpp traindialog.h \
		ednetwork.h \
		globals.h \
		greyscalewindow.h \
		ednetworkmember.h \
		edgeconfiguration.h \
		edsubnetwork.h \
		neuron.h \
		dtneuron.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o traindialog.o traindialog.cpp

xnned.o: xnned.cpp xnned.h \
		ednetwork.h \
		globals.h \
		greyscalewindow.h \
		ednetworkmember.h \
		edgeconfiguration.h \
		edsubnetwork.h \
		neuron.h \
		dtneuron.h \
		traindialog.h \
		nedtreeview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xnned.o xnned.cpp

moc_nedtreeview.o: moc_nedtreeview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nedtreeview.o moc_nedtreeview.cpp

moc_traindialog.o: moc_traindialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_traindialog.o moc_traindialog.cpp

moc_xnned.o: moc_xnned.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_xnned.o moc_xnned.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

